api:

  # These defaults can be overridden with the following environment variables:
  #   ENV['LIBSASS_ENDPOINT']
  #   ENV['SASS_34_ENDPOINT']

  development: &default_settings
    endpoints:
      lib: 'http://lib.sassmeister.dev'
      '3.3': 'http://sass3-3.sassmeister.dev'
      '3.4': 'http://sass3-4.sassmeister.dev'
      '4.0': 'http://sass4-0alpha.sassmeister.dev'

  test:
    <<: *default_settings

  production:
    endpoints:
      lib: 'http://libsass.api.sassmeister.com'
      '3.3': 'http://sassmeister-33.herokuapp.com'
      '3.4': 'http://sassmeister-34.herokuapp.com'
      '4.0': 'http://sassmeister40alpha.herokuapp.com'

