development: &default_settings
  app_version: '2.0.1'
  session_duration: 7776000 # 90 days, in seconds
  cache_max_age: 0
  cookie_domain: 'local.sassmeister.com'
  cookie_secret: 'dev'
  app_domain: 'http://local.sassmeister.com:9292'
  embed_domain: 'http://embed-local.sassmeister.com:9292'
  sandbox_domain: 'http://sandbox.sassmeister.dev'
  asset_domain: ''
  asset_suffix: ''

test:
  <<: *default_settings

production:
  <<: *default_settings
  cache_max_age: 300 # 5 minutes
  cookie_domain: '.sassmeister.com'
  app_domain: 'https://www.sassmeister.com'
  embed_domain: 'https://embed.sassmeister.com'
  sandbox_domain: 'https://sandbox.sassmeister.com'
  asset_domain: 'https://cdn.sassmeister.com'
  asset_suffix: '.min'

