"Blend Modes":
  :gem: blend-mode
  :import: 
    - blend-mode
  :url: https://github.com/heygrady/scss-blend-modes
Bourbon:
  :gem: bourbon-compass
  :import: 
    - bourbon/bourbon
  :url: http://bourbon.io/
Breakpoint:
  :gem: breakpoint
  :import: 
    - breakpoint
  :url: https://github.com/canarymason/breakpoint
"Breakpoint Slicer":
  :gem: breakpoint-slicer
  :import:
    - breakpoint-slicer
  :url: https://github.com/lolmaus/breakpoint-slicer
"Color Schemer":
  :gem: color-schemer
  :import: 
    - color-schemer
  :url: https://github.com/Team-Sass/color-schemer
Compass:
  :gem: compass
  :import: 
    - compass
  :url: http://compass-style.org
"Compass Slideshow":
  :gem: css-slideshow
  :import: 
    - css-slideshow
  :url: https://github.com/ericam/compass-css-slideshow
"Fancy Buttons":
  :gem: fancy-buttons
  :import: 
    - fancy-buttons
  :url: http://brandonmathis.com/projects/fancy-buttons/
Fittext:
  :gem: fittext
  :import: 
    - fittext
  :url: http://www.bookcasey.com/fittext/
Harsh:
  :gem: harsh
  :import: 
    - harsh
  :url: http://www.bookcasey.com/harsh/
Jacket:
  :gem: jacket
  :import:
    - jacket
  :url: https://github.com/Team-Sass/jacket
"Modular Scale":
  :gem: modular-scale
  :import: 
    - modular-scale
  :url: https://github.com/Team-Sass/modular-scale
Neat:
  :gem: neat-compass
  :import:
    - bourbon/bourbon
    - neat/neat
  :url: http://neat.bourbon.io
'Normalize':
  :gem: normalize-scss
  :import:
    - normalize
  :url: https://github.com/JohnAlbin/normalize.css-with-sass-or-compass
"Responsive Calculator":
  :gem: rwdcalc
  :import: 
    - rwdcalc
  :url: https://github.com/sturobson/Responsive-Calculator/tree/rwdcalcSass/SCSSMixin
"Responsive Sass":
  :gem: responsive-sass
  :import: 
    - responsive-sass
  :url: http://ntreadway.github.com/responsive-sass/welcome
Salsa:
  :gem: salsa
  :import: 
    - salsa
  :url: http://tsi.github.com/Salsa/
"Sassy Buttons":
  :gem: sassy-buttons
  :import: 
    - sassy-buttons
  :url: http://jaredhardy.com/sassy-buttons/
"Sassy Math":
  :gem: sassy-math
  :import: 
    - '' # This space intentionally left blank 
  :url: https://github.com/Team-Sass/Sassy-math
"Sassy Text Shadows":
  :gem: sassy-text-shadow
  :import:
    - compass
    - sassy-text-shadow
  :url: http://sassymothereffingtextshadow.com/
"SCSS Blend Modes":
  :gem: compass-blend-modes
  :import: 
    - blend-modes
  :url: https://github.com/heygrady/scss-blend-modes
Singularity.gs:
  :gem: singularitygs
  :import: 
    - singularitygs
  :url: https://github.com/Team-Sass/singularity
"Singularity Extras":
  :gem: singularity-extras
  :import:
    - singularitygs
    - singularity-extras
  :url: https://github.com/Team-Sass/Singularity-extras
Stipe:
  :gem: stipe
  :import: 
    - stipe/manifest
    - stipe/grid/extends
  :url: https://github.com/Toadstool-Stipe/stipe
Susy:
  :gem: susy
  :import: 
    - susy
  :url: http://susy.oddbird.net
Toolkit:
  :gem: toolkit
  :import: 
    - toolkit
  :url: https://github.com/Team-Sass/toolkit
"Zen Grids":
  :gem: zen-grids
  :import: 
    - zen
  :url: http://zengrids.com/